blank_issues_enabled: true
contact_links:
  - name: Something else?
    url: https://github.com/toeverything/AFFiNE/discussions
    about: Please ask and answer support questions here
  - name: AFFiNE Community Support
    url: https://community.affine.pro
    about: AFFiNE Community page - a place to ask, learn and engage with others
