blank_issues_enabled: true
contact_links:
  - name: Something else?
    url: https://github.com/toeverything/AFFiNE/discussions
    about: Please ask and answer support questions here.
  - name: AFFiNE Community Support
    url: https://community.affine.pro
    about: You can ask and answer questions, while meeting new users.
